"""empty message

Revision ID: af39e3a74e06
Revises: 
Create Date: 2019-07-10 15:50:40.770788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af39e3a74e06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxi', sa.Column('lat', sa.String(length=64), nullable=True))
    op.add_column('taxi', sa.Column('lon', sa.String(length=64), nullable=True))
    op.add_column('taxi', sa.Column('timestamp', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taxi', 'timestamp')
    op.drop_column('taxi', 'lon')
    op.drop_column('taxi', 'lat')
    # ### end Alembic commands ###
